### ISSUE TITLE
[cPP CHANGE] FCS_STO_EXT.1 & Application Note 2

### ISSUE THREAD

**Issue by woodbe** [appswcpp/repository#6]
**What is the change request for the cPP? Please describe.**
I don't think it is allowed to specify the requirement to include FCP_COP.1/DataEncryption by the app note. 

I am not certain about the last sentence in the app note that says other operations may be needed. If there are other possible options, they should be written in as a selection for that choice (i.e. make the example below a selection within the selection and list out the FCS SFRs that may be applicable).

**Describe the solution you'd like**
Change the SFR to the following (bold text used to show the change):
> FCS_STO_EXT.1.1 The application shall [_selection: not store any credentials, invoke the functionality provided by the platform to securely store [assignment: list of credentials], implement functionality to securely store [assignment: list of credentials] **using FCS_COP.1/DataEncryption**_] to non-volatile memory.

Then remove this sentence from Application Note 2
> If implement functionality to securely store credentials is selected, then the following components must be included in the ST: FCS_COP.1/DataEncryption.

**Describe alternatives you've considered**
N/A

**Additional context**
While the language may be tweaked (not sure about "using" in this phrase), this explicitly mandates that this needs to be done according to FCS_COP.1/DataEncryption.

**Comment by Kneckter** [comment]
Related to this issue and issue #28, the SD lists `FCS_CKM.1` as a second option but this isn't in the PP's SFR. I think the reference in the SD was to the PBKDF that NIAP had in their AS PP so the SFR reference isn't accurate. Is the intent to disallow PBKDFs moving forward? If not, FCS_COP.1/DataEncryption would need to be selectable as using a PBKDF isn't encryption but has hashing requirements instead. There would also need to be an SFR for hashing like NIAP's `FCS_CKM.1(3) Password Conditioning` (but reformatted since it doesn't follow the CC standard of iterating an SFR).

This SFR may need some tweaking as using FCS_COP.1 or FCS_CKM.1(3) would cover the securing of credentials but not the storing of them. There should be an assignment to note the storage location similar to this:

> FCS_STO_EXT.1.1 The application shall [selection: not store any credentials, invoke the functionality provided by the platform to securely store [assignment: list of credentials], implement functionality to securely store [assignment: list of credentials] **in [assignment: storage locations] using [selection: FCS_COP.1/DataEncryption, FCS_CKM.1(3)]]** to non-volatile memory.

**Comment by bharveyTX** [comment]
We made the following change to the SFR:

*FCS_STO_EXT.1.1* The application shall [_selection: not store any credentials, invoke the functionality provided by the platform to securely store [assignment: list of credentials], implement functionality to securely store [assignment: list of credentials_] according to [_selection: FCS_COP.1/DataEncryption, FCS_CKM.1/Hash, FCS_CKM.1/KeyedHash_] to non-volatile memory.

explicit PBKDF inclusion via it's own SFR is still being considered by the iTC. 

@Kneckter Please open a PBKDF feature request if desired.
