### ISSUE TITLE
[cPP CHANGE] Document Selection Criteria for Selection-Based SFRs

### ISSUE THREAD

**Issue by robertmclemons** [appswcpp/repository#63]
**What is the change request for the cPP? Please describe.**
The below are selection-based SFRs where the AppNote does not explain the selection criteria:
FCS_CKM.1
FCS_CKM.2
FCS_COP.1/DataEncryption
FCS_COP.1/SigGen
FCS_COP.1/Hash
FCS_COP.1/KeyedHash
FCS_HTTPS_EXT.1 (selected in DIT)
FCS_SSH_EXT.1 (selected in DIT) (BTW, why not use the SSH FP?)
FIA_X509_EXT.1/2

**Describe the solution you'd like**
Describe the selections that invoke these requirements in the AppNotes. 

**Describe alternatives you've considered**
A clear and concise description of any alternative solutions you've considered using the existing cPP requirements.

**Additional context**
Add any other context or screenshots about the change request here.

**Comment by bharveyTX** [comment]
We have implemented links to selective-based SFRs in the newest draft such as in FTP_DIT_EXT.1. Does this meet the expectation of this issue?

Also, we did not link to the SSH FP because it is a national package and we were concerned about linking for the cPP. The contents were therefore reproduced in whole within the cPP.

**Comment by bharveyTX** [comment]
We have decided to include the SSH package in the cPP and it will be implemented in version 1.0.
