### ISSUE TITLE
[cPP CHANGE] FMT_SMF.1  and updating TOE

### ISSUE THREAD

**Issue by avcode79** [appswcpp/repository#77]
**On behalf of CCCS**
cPP FMT_SMF.1 Why is updating the TOE not a management function? Why is configuration of keys/PKI not a management function?

**Comment by bharveyTX** [comment]
Due to the wide nature of applicable applications (such as single user desktop apps) the functionality to perform updates or configure keys is not mandatory. This functionality may be implemented or facilitated by the platform.

For this reason, we do not feel that adding explicit selections in FMT_SMF.1 is appropriate. If this functionality is implemented by the TOE, the assignment for other management functionality is allowed in FMT_SMF.1.
