### ISSUE TITLE
[SD CHANGE] Type 4 Hypothesis

### ISSUE THREAD

**Issue by avcode79** [appswcpp/repository#89]
**On behalf of the CCCS**
SD page 74 para 333 A.1.4 Type 4 Hypothesis based on fuzz testing a network interface is not applicable to most TOE types in this cPP, essentially resulting in testing the underlying OS instead of the TOE. An alternative Type 4 proposal is included in a separate document.
[SWcPP - tool generated hypotheses.docx](https://github.com/appswcpp/repository/files/7469987/SWcPP.-.tool.generated.hypotheses.docx)

**Comment by avcode79** [comment]
Reviewed the recommendations and decided to adopt the Vulnerability Scanning option. The other methods were considered either not feasible (e.g. static code analysis would require access to source code) or of limited value (e.g. fuzz testing).

**Comment by acumensec** [comment]
Note for iTC:
Update Type 4 hypothesis as follows:
Automated vulnerability scanning is a method where a specialized tool is applied to a specific attack surface in order to test it for the presence of known types of vulnerabilities. If this approach is technically feasible, the expectation is that the vulnerability scanning is conducted by the evaluator within a controlled test environment. The evaluator must ensure that the TOE is directly reachable and there is no network traffic filtering device, like a firewall, between the scanner and the TOE. 
Vulnerability scanners are known to produce recommendations for hardening along with possible vulnerabilities. There is no expectation that all recommendations produced by such tool must be implemented. However, each reported vulnerability must be investigated and resolved or classified as a false positive.

**Comment by bharveyTX** [comment]
Incorporated into SD
